# -*- coding: utf-8 -*-

data = {
	0: {
		'name': 'Healing Seeds',
		'id': 1,
		'description': 'Sews several seeds of health to heal the target for %a over %s.',
		'scriptName': 'HoTAbility',
		'icon': 'Ability_26',
		'type': 'PeriodicHealing',
		'cost': 0.05,
		'costType': 'Energy',
		'range': 0,
		'castTime': 1,
		'cooldown': 7.5,
		'amount': 0.025,
		'amountBasedFrom': 'AbilityPower',
		'auraOne': -1,
		'auraTwo': -1,
		'auraThree': -1,
		},
	1: {
		'name': 'Corruption',
		'id': 2,
		'description': 'Corrupts the target, causing %a %t damage over %s seconds.',
		'scriptName': 'DoTAbility',
		'icon': 'Ability_02',
		'type': 'PeriodicDamage',
		'cost': 0.075,
		'costType': 'Health',
		'range': 0,
		'castTime': 1.5,
		'cooldown': 0.5,
		'amount': 0,
		'amountBasedFrom': 'AbilityPower',
		'auraOne': 1,
		'auraTwo': -1,
		'auraThree': -1,
		},
	2: {
		'name': 'Tendrils of Fate',
		'id': 3,
		'description': 'Several Tendrils of the apocalypse come out to saturate the target with dark energy.',
		'scriptName': 'PullAbility',
		'icon': 'Ability_07',
		'type': 'Pull',
		'cost': 0.15,
		'costType': 'Energy',
		'range': 0,
		'castTime': 3,
		'cooldown': 15,
		'amount': 0.015,
		'amountBasedFrom': 'AttackPower',
		'auraOne': 2,
		'auraTwo': -1,
		'auraThree': -1,
		},
	3: {
		'name': 'Variety Heal',
		'id': 4,
		'description': 'A varien heal of %a to the target.',
		'scriptName': 'HealAbility',
		'icon': 'Ability_06',
		'type': 'Healing',
		'cost': 0.05,
		'costType': 'Energy',
		'range': 0,
		'castTime': 2.5,
		'cooldown': 0,
		'amount': 0.225,
		'amountBasedFrom': 'AbilityPower',
		'auraOne': -1,
		'auraTwo': -1,
		'auraThree': -1,
		}
	}

allData = {
	'AbilityInitialization': data
}

