# -*- coding: utf-8 -*-

data = {
	0: {
		'name': 'Corruption',
		'id': 1,
		'description': 'Welcome to the dark side!',
		'scriptName': 'HarmfulAura',
		'school': 'Shadow',
		'icon': 'Auras_Blood_Bleed_1',
		'type': 'DamageOverTime',
		'amount': 0.02,
		'duration': 12,
		'period': 3,
		'effectTarget': 4,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 3,
		'effectApplyAttribute': 2,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	1: {
		'name': 'Devouring Plague',
		'id': 2,
		'description': 'You are getting eaten from the inside out!',
		'scriptName': 'HarmfulAura',
		'school': 'Dark',
		'icon': 'Aura_31',
		'type': 'DamageOverTime',
		'amount': 0.02,
		'duration': 30,
		'period': 3,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 3,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	2: {
		'name': 'A Little Fortitude',
		'id': 3,
		'description': '',
		'scriptName': 'HelpfulAura',
		'school': 'Physical',
		'icon': 'Aura_20',
		'type': 'Special',
		'amount': 0.05,
		'duration': 300,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	3: {
		'name': 'A Bit of Fortitude',
		'id': 4,
		'description': '',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': 'Aura_28',
		'type': 'Special',
		'amount': 0.07,
		'duration': 300,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	4: {
		'name': 'A Lot of Fortitude',
		'id': 5,
		'description': '',
		'scriptName': 'HelpfulAura',
		'school': 'Physical',
		'icon': 'Aura_29',
		'type': 'Special',
		'amount': 0.11,
		'duration': 300,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	5: {
		'name': 'Wrath of Dounia',
		'id': 6,
		'description': 'Dounia is very upset with you.',
		'scriptName': 'HarmfulAura',
		'school': 'Nature',
		'icon': 'Aura_05',
		'type': 'DamageOverTime',
		'amount': 0,
		'duration': 60,
		'period': 6,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	6: {
		'name': 'Drunk',
		'id': 7,
		'description': 'You are completely slooshed!',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': 'Aura_16',
		'type': 'Confusion',
		'amount': 0,
		'duration': 300,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	7: {
		'name': 'Chain Trauma',
		'id': 8,
		'description': 'Your ankles have been chafed by the chains, the wounds causing you to not walk properly.[Add Type:Slow]',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'DamageOverTime',
		'amount': 0,
		'duration': 11,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	8: {
		'name': 'Burning',
		'id': 9,
		'description': 'You\'re on fire! ...and not in the good way!',
		'scriptName': 'HarmfulAura',
		'school': 'Fire',
		'icon': '',
		'type': 'DamageOverTime',
		'amount': 0.01,
		'duration': 6,
		'period': 2,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 3,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	9: {
		'name': 'Freezing',
		'id': 10,
		'description': 'Ice is coursing through your veins.',
		'scriptName': 'HarmfulAura',
		'school': 'Frost',
		'icon': '',
		'type': 'DamageOverTime',
		'amount': 0.01,
		'duration': 6,
		'period': 2,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 3,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	10: {
		'name': 'Power Swap',
		'id': 11,
		'description': 'Attack Power and Defense Power swap values.',
		'scriptName': 'HarmfulAura',
		'school': 'None',
		'icon': '',
		'type': 'Special',
		'amount': 0,
		'duration': 30,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	11: {
		'name': 'Life\'s Blessing',
		'id': 12,
		'description': 'Life herself blesses you with increased regeneration.',
		'scriptName': 'HelpfulAura',
		'school': 'Nature',
		'icon': '',
		'type': 'HealOverTime',
		'amount': 0.11,
		'duration': 15,
		'period': 3,
		'effectTarget': 0,
		'effectTargetType': 3,
		'effectTargetAttribute': 0,
		'effectCalculation': 3,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	12: {
		'name': 'Tremble',
		'id': 13,
		'description': 'You\'re having an allergic reaction to courage.',
		'scriptName': 'HarmfulAura',
		'school': 'Dark',
		'icon': '',
		'type': 'Fear',
		'amount': 0,
		'duration': 5,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	13: {
		'name': 'Petrified',
		'id': 14,
		'description': 'Every cell in your body has turned to stone!',
		'scriptName': 'HarmfulAura',
		'school': 'Mud',
		'icon': '',
		'type': 'Stun',
		'amount': 0,
		'duration': 5,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	14: {
		'name': 'Dimension Protection',
		'id': 15,
		'description': 'You are immune to any Spatial crowd control effects.',
		'scriptName': 'HelpfulAura',
		'school': 'Spatial',
		'icon': '',
		'type': 'Immunity',
		'amount': 0,
		'duration': 5,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	15: {
		'name': 'Got \'Em',
		'id': 16,
		'description': 'Grows roots underneath your targets that reach up and entangle their feet, causing them to stay in place.',
		'scriptName': 'HarmfulAura',
		'school': 'Nature',
		'icon': '',
		'type': 'Root',
		'amount': 0,
		'duration': 5,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	16: {
		'name': 'Blind',
		'id': 17,
		'description': 'You cannot see!',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'Special',
		'amount': 0,
		'duration': 0,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	17: {
		'name': 'Stunned',
		'id': 18,
		'description': 'You are out of commission!',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'Stun',
		'amount': 0,
		'duration': 3,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	18: {
		'name': 'Mildly Confused',
		'id': 19,
		'description': 'What is who? Where is why? How is when?',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'Confusion',
		'amount': 0,
		'duration': 7,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	19: {
		'name': 'Slightly Confused',
		'id': 20,
		'description': 'Wait a minute... what? Hmm...',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'Confusion',
		'amount': 0,
		'duration': 3,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		},
	20: {
		'name': 'Greatly Confused',
		'id': 21,
		'description': '...??!?!?!?!!?!!??!!!...',
		'scriptName': 'HarmfulAura',
		'school': 'Physical',
		'icon': '',
		'type': 'Confusion',
		'amount': 0,
		'duration': 11,
		'period': 0,
		'effectTarget': 0,
		'effectTargetType': 1,
		'effectTargetAttribute': 0,
		'effectCalculation': 0,
		'effectApplyAttribute': 0,
		'effectTargetTypeRange': 0,
		'effectTargetTypeMaxReceivers': 0,
		}
}

allData = {
	'AuraInitialization': data
}

