EMPTY_SLOT = -1  # Empty inventory  value
INVENTORY_OPERATION_ERROR = -1	 # Invalid inventory operation value
INVENTORY_OPERATION_FULL = -2
INVENTORY_OPERATION_EMPTY_SOURCE = -3 # Invalid source input
INVENTORY_OPERATION_EMPTY_DESTINATION = -7 # Invalid destination input
INVENTORY_OPERATION_ITEM_NONEXISTENT = -4
INVENTORY_OPERATION_INVALID_INDEX = -5	 # Invalid inventory operation value
INVENTORY_OPERATION_INVALID_COUNT = -6
INVENTORY_OPERATION_OK = 99

GC_OK = 0x000

#Guild Rankings

LEADER = 0
CO_LEADER = 1
MEMBER = 2

#Guild Parameters
GUILD_NAME_LIMIT = 32
GUILD_CAPACITY = 50
GUILD_NOTICE_MAX_LENGTH = 128
GUILD_CREATION_PRICE = 2000

#Party & Raid
PARTY_CAPACITY = 5
MICRO_RAID_CAPACITY = 10
MINI_RAID_CAPACITY = 15
RAID_CAPACITY = 40

#Chat
CHAT_CHANNEL_GLOBAL_CAPACITY = 5