EMPTY_SLOT = -1  # Empty inventory  value
INVENTORY_OPERATION_ERROR = -1	 # Invalid inventory operation value


#Guild Rankings

LEADER = 0
CO_LEADER = 1
MEMBER = 2

#Guild Parameters
GUILD_NAME_LIMIT = 32
GUILD_CAPACITY = 50
GUILD_NOTICE_MAX_LENGTH = 128
GUILD_CREATION_PRICE = 2000

#Party & Raid
PARTY_CAPACITY = 5
MICRO_RAID_CAPACITY = 10
MINI_RAID_CAPACITY = 15
RAID_CAPACITY = 40